services:
  bot:
    build:
      context: ./src
      dockerfile: ./docker/bot/Dockerfile
    environment:
      - BOT_SERVER_PORT=${BOT_SERVER_PORT}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - REALTIME_SERVICE_URI=${REALTIME_SERVICE_URI}
  mongodb:
    image: mongo:latest
    volumes:
      - database:/data/db
  ratings:
    build:
      context: ./src
      dockerfile: ./docker/ratings/Dockerfile
    environment:
      - RATINGS_REQUEST_URL=${RATINGS_REQUEST_URL}
      - RATINGS_SERVER_PORT=${RATINGS_SERVER_PORT}
  ratings_history:
    build:
      context: ./src
      dockerfile: ./docker/ratings_history/Dockerfile
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_COLLECTION_NAME=${DATABASE_COLLECTION_NAME}
      - DATABASE_CONNECT_TIMEOUT=${DATABASE_CONNECT_TIMEOUT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URI=${DATABASE_URI}
      - RATINGS_HISTORY_SERVER_PORT=${RATINGS_HISTORY_SERVER_PORT}
  realtime:
    build:
      context: ./src
      dockerfile: ./docker/realtime/Dockerfile
    environment:
      - RATINGS_SERVICE_URI=${RATINGS_SERVICE_URI}
      - RATINGS_HISTORY_SERVICE_URI=${RATINGS_HISTORY_SERVICE_URI}
      - REALTIME_SERVER_PORT=${REALTIME_SERVER_PORT}
      - TICKER_SERVICE_URI=${TICKER_SERVICE_URI}
  refresher:
    build:
      context: ./src
      dockerfile: ./docker/refresher/Dockerfile
    environment:
      - BOT_SERVICE_URI=${BOT_SERVICE_URI}
      - RATINGS_HISTORY_SERVICE_URI=${RATINGS_HISTORY_SERVICE_URI}
      - REALTIME_SERVICE_URI=${REALTIME_SERVICE_URI}
      - REFRESHER_SYMBOLS=${REFRESHER_SYMBOLS}
  ticker:
    build:
      context: ./src
      dockerfile: ./docker/ticker/Dockerfile
    environment:
      - TICKER_SERVER_PORT=${TICKER_SERVER_PORT}
volumes:
  database: {}
