FROM golang:1.16-alpine

# Copy and install ticker dependencies
COPY /go/ticker/go.mod /usr/src/go.mod
COPY /go/ticker/go.sum /usr/src/go.sum
RUN set -xe; \
    cd /usr/src; \
    go mod download;

WORKDIR /usr/src/app/ticker
CMD [ "go", "run", "ticker.go" ]