FROM golang:1.16-alpine

# Copy and install refresher dependencies
COPY /go/refresher/go.mod /usr/src/go.mod
RUN set -xe; \
    cd /usr/src; \
    go mod download;

WORKDIR /usr/src/app/refresher
CMD [ "go", "run", "refresher.go" ]